spring:
  application:
    name: paiement
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 1000

server:
  port: 8085
